"""Export utilities: JSON, SQL, SVG, PNG (pure-Python), PDF (pure-Python)."""
from __future__ import annotations

import struct
import zlib
from typing import Any


def export_json(metadata: dict[str, Any]) -> bytes:
    import json

    return json.dumps(metadata, indent=2, default=str).encode("utf-8")


def export_sql(schema_sql: str, data_dump: str) -> bytes:
    header = (
        "-- Database schema dump\n"
        "-- Generated by Database Visualizer & SQL Workspace\n\n"
    )
    body = schema_sql + "\n" + data_dump
    return (header + body).encode("utf-8")


# --- SVG ---------------------------------------------------------------------


def export_svg(metadata: dict[str, Any]) -> bytes:
    schema = metadata.get("schemas", [{}])[0] if metadata.get("schemas") else {}
    tables = schema.get("tables", [])
    box_w = 220
    row_h = 18
    header_h = 24
    padding = 40
    gap_x = 60
    gap_y = 40
    cols_per_row = 3

    boxes: list[dict[str, Any]] = []
    for i, t in enumerate(tables):
        col_count = max(1, len(t.get("columns", [])))
        box_h = header_h + col_count * row_h + 6
        col = i % cols_per_row
        row = i // cols_per_row
        x = padding + col * (box_w + gap_x)
        y = padding + row * (box_h + gap_y)
        boxes.append({"table": t, "x": x, "y": y, "w": box_w, "h": box_h})

    if not boxes:
        width = 400
        height = 200
    else:
        width = (
            padding * 2
            + cols_per_row * box_w
            + (cols_per_row - 1) * gap_x
        )
        max_y = max((b["y"] + b["h"]) for b in boxes)
        height = padding * 2 + max_y - padding
        # Recompute width if fewer tables.
        n_cols = min(cols_per_row, max(1, len(boxes)))
        width = padding * 2 + n_cols * box_w + max(0, n_cols - 1) * gap_x
        height = padding * 2 + max_y

    parts: list[str] = []
    parts.append(
        f'<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{height}" viewBox="0 0 {width} {height}">'
    )
    parts.append('<rect width="100%" height="100%" fill="#fafafa"/>')

    # Table boxes.
    for b in boxes:
        t = b["table"]
        x, y, w, h = b["x"], b["y"], b["w"], b["h"]
        parts.append(
            f'<g><rect x="{x}" y="{y}" width="{w}" height="{h}" '
            f'rx="6" fill="#ffffff" stroke="#333" stroke-width="1"/>'
            f'<rect x="{x}" y="{y}" width="{w}" height="{header_h}" '
            f'rx="6" fill="#4f46e5"/>'
            f'<text x="{x + 8}" y="{y + 16}" fill="#fff" '
            f'font-family="sans-serif" font-size="13" font-weight="bold">'
            f'{_esc(t["name"])}</text>'
        )
        for j, c in enumerate(t.get("columns", [])):
            cy = y + header_h + 8 + j * row_h
            pk = "PK " if c.get("is_pk") else ""
            fk = "FK " if c.get("is_fk") else ""
            label = f"{pk}{fk}{c['name']}: {c.get('data_type', '')}"
            parts.append(
                f'<text x="{x + 10}" y="{cy}" fill="#222" '
                f'font-family="monospace" font-size="11">{_esc(label)}</text>'
            )
        parts.append("</g>")

    # FK lines.
    name_to_box: dict[str, dict[str, Any]] = {b["table"]["name"]: b for b in boxes}
    for b in boxes:
        t = b["table"]
        for fk in t.get("foreign_keys", []):
            parent = name_to_box.get(fk["to_table"])
            if not parent:
                continue
            x1 = b["x"] + b["w"]
            y1 = b["y"] + b["h"] // 2
            x2 = parent["x"]
            y2 = parent["y"] + parent["h"] // 2
            parts.append(
                f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
                f'stroke="#ef4444" stroke-width="1.5"/>'
            )

    parts.append("</svg>")
    return "\n".join(parts).encode("utf-8")


def _esc(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# --- PNG (pure-Python) ------------------------------------------------------


def export_png(metadata: dict[str, Any]) -> bytes:
    """Render a minimal PNG with colored rectangles for each table.

    Uses only stdlib struct + zlib. No pillow dependency.
    """
    schema = metadata.get("schemas", [{}])[0] if metadata.get("schemas") else {}
    tables = schema.get("tables", [])

    width = 640
    height = 480
    # Build an RGB image with a background.
    bg = (250, 250, 250)
    palette = [
        (79, 70, 229),
        (16, 185, 129),
        (245, 158, 11),
        (239, 68, 68),
        (59, 130, 246),
        (139, 92, 246),
    ]

    # Raw pixel buffer (height rows of width*3 bytes).
    rows = []
    for _y in range(height):
        rows.append(bytearray(bg[0] for _ in range(width * 3)))
    for i in range(height):
        for x in range(width):
            base = x * 3
            rows[i][base] = bg[0]
            rows[i][base + 1] = bg[1]
            rows[i][base + 2] = bg[2]

    # Draw rectangles.
    n = len(tables)
    if n:
        cols = 3
        box_w = (width - 60) // cols - 10
        box_h = 50
        x0 = 20
        y0 = 20
        for idx, t in enumerate(tables):
            col = idx % cols
            row = idx // cols
            rx = x0 + col * (box_w + 10)
            ry = y0 + row * (box_h + 10)
            color = palette[idx % len(palette)]
            _fill_rect(rows, rx, ry, box_w, box_h, color, width, height)

    return _encode_png(rows, width, height)


def _fill_rect(
    rows: list[bytearray],
    x: int,
    y: int,
    w: int,
    h: int,
    color: tuple[int, int, int],
    width: int,
    height: int,
) -> None:
    x2 = min(x + w, width)
    y2 = min(y + h, height)
    for yy in range(max(0, y), y2):
        for xx in range(max(0, x), x2):
            base = xx * 3
            rows[yy][base] = color[0]
            rows[yy][base + 1] = color[1]
            rows[yy][base + 2] = color[2]


def _encode_png(rows: list[bytearray], width: int, height: int) -> bytes:
    """Encode raw RGB rows as a PNG using struct + zlib."""
    raw = bytearray()
    for row in rows:
        raw.append(0)  # filter type 0 (None)
        raw.extend(row)

    def _chunk(tag: bytes, data: bytes) -> bytes:
        chunk = struct.pack(">I", len(data)) + tag + data
        crc = zlib.crc32(tag + data) & 0xFFFFFFFF
        return chunk + struct.pack(">I", crc)

    signature = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)  # 8-bit, color type 2 (RGB)
    idat = zlib.compress(bytes(raw), 9)
    return signature + _chunk(b"IHDR", ihdr) + _chunk(b"IDAT", idat) + _chunk(b"IEND", b"")


# --- PDF (pure-Python) -------------------------------------------------------


def export_pdf(metadata: dict[str, Any]) -> bytes:
    """Generate a minimal single-page PDF listing the schema as text."""
    schema = metadata.get("schemas", [{}])[0] if metadata.get("schemas") else {}
    tables = schema.get("tables", [])

    lines: list[str] = []
    lines.append("Database Schema Report")
    lines.append("=======================")
    lines.append("")
    if not tables:
        lines.append("No tables found.")
    for t in tables:
        lines.append(f"Table: {t['name']}  (rows: {t.get('row_count', 0)})")
        for c in t.get("columns", []):
            pk = "PK " if c.get("is_pk") else ""
            fk = "FK " if c.get("is_fk") else ""
            lines.append(f"  {pk}{fk}{c['name']} {c.get('data_type', '')}")
        lines.append("")

    return _encode_pdf(lines)


def _encode_pdf(lines: list[str]) -> bytes:
    """Encode text lines as a minimal one-page PDF."""
    page_width = 612
    page_height = 792
    margin = 50
    line_height = 14
    start_y = page_height - margin

    # Build content stream.
    content_lines = ["BT", f"/F1 12 Tf", f"1 0 0 1 {margin} {start_y} Tm"]
    y = 0
    for line in lines:
        safe = line.replace("(", r"\(").replace(")", r"\)")
        content_lines.append(f"{safe} Tj 0 -{line_height} Td")
    content_lines.append("ET")
    content = "\n".join(content_lines)
    content_bytes = content.encode("latin-1", "replace")

    objects: list[bytes] = []

    # Object 1: Catalog
    obj1 = b"<< /Type /Catalog /Pages 2 0 R >>"
    # Object 2: Pages
    obj2 = b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>"
    # Object 3: Page
    obj3 = (
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 "
        + str(page_width).encode()
        + b" "
        + str(page_height).encode()
        + b"] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>"
    )
    # Object 4: Contents
    obj4 = (
        b"<< /Length " + str(len(content_bytes)).encode() + b" >>\nstream\n"
        + content_bytes + b"\nendstream"
    )
    # Object 5: Font
    obj5 = b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"

    objects.extend([obj1, obj2, obj3, obj4, obj5])

    pdf = bytearray()
    pdf.extend(b"%PDF-1.4\n")
    offsets: list[int] = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{i} 0 obj\n".encode())
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")

    xref_offset = len(pdf)
    pdf.extend(b"xref\n")
    pdf.extend(f"0 {len(objects) + 1}\n".encode())
    pdf.extend(b"0000000000 65535 f \n")
    for off in offsets:
        pdf.extend(f"{off:010d} 00000 n \n".encode())
    pdf.extend(b"trailer\n")
    pdf.extend(f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n".encode())
    pdf.extend(b"startxref\n")
    pdf.extend(f"{xref_offset}\n".encode())
    pdf.extend(b"%%EOF")
    return bytes(pdf)